service: serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1

plugins:
  - serverless-sync-s3buckets


resources:
  Resources:
    SmoothOperatorsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: Delete
      Properties:
        BucketName: batch2024-smooth-operators
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    SmoothOperatorsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: SmoothOperatorsBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join:
                  ["", ["arn:aws:s3:::", { "Ref": SmoothOperatorsBucket}, "/*"]]

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: SmoothOperatorsOrigin
              DomainName:
                { "Fn::GetAtt": ["SmoothOperatorsBucket", "RegionalDomainName"] }
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: "true"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: SSmoothOperatorsBucketOrigin
            ForwardedValues:
              QueryString: "false"
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: "true"

  Outputs:
    SmoothOperatorsBucketName:
      Value: { "Ref": "SmoothOperatorsBucket" }
    SmoothOperatorsSiteURL:
      Value: { "Fn::GetAtt": ["CloudFrontDistribution", "DomainName"] }

custom:
  syncS3Buckets:
    - bucketRef: SmoothOperatorsBucket
      localDir: dist/final-ui