service: batch2024-smooth-operators
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1

plugins:
  - serverless-sync-s3buckets

functions:
  smooth-operators-Getprojects:
    handler: smooth-operators-Getprojects/handler.handler
    events:
      - http:
          path: /projects
          method: get

resources:
  Resources:
    SmoothOperatorsProjectTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: smooth-operators-project-table
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
  
    SmoothOperatorsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: batch2024-smooth-operators
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false

    SmoothOperatorsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref SmoothOperatorsBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: !Join ["", ["arn:aws:s3:::", !Ref SmoothOperatorsBucket, "/*"]]

    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Origins:
            - Id: SmoothOperatorsOrigin
              DomainName: !GetAtt SmoothOperatorsBucket.RegionalDomainName
              S3OriginConfig:
                OriginAccessIdentity: ""

          Enabled: true
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: SmoothOperatorsOrigin
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

  Outputs:
    SmoothOperatorsBucketName:
      Value: !Ref SmoothOperatorsBucket
    SmoothOperatorsSiteURL:
      Value: !GetAtt CloudFrontDistribution.DomainName
