name: Deploy to S3

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli

    - name: Install dependencies
      run: yarn

    - name: Build project
      run: yarn build

    - name: Install Serverless Framework and Plugins
      run: |
        npm install -g serverless
        npm install -g serverless-s3-sync

    - name: Deploy with Serverless Framework
      working-directory: smooth
      run: serverless deploy
