name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
        
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy to S3 bucket
      run: |
        aws s3 sync dist/final-ui s3://batch2024-smooth1 --delete --region ca-central-1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
    - name: Create CloudFront distribution
      run: |
        aws cloudfront create-distribution --distribution-config file://cloudfront-config.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
