name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        
    - name: Install dependencies
      run: yarn
      
    - name: Build project
      run: yarn build
      
    - name: Create S3 bucket 
      run: |
        aws s3 mb s3://batch2024-smooth --region ca-central-1 2>&1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      
    - name: Deploy to S3 bucket
      run: |
        aws s3 sync dist/final-ui s3://batch2024-smooth --delete --region ca-central-1
      
    - name: Create CloudFront distribution
      run: |
        aws cloudfront create-distribution --origin-domain-name batch2024-smooth1.s3.amazonaws.com --default-root-object index.html
