name: Deploy Angular App to AWS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Angular CLI and Dependencies
        run: |
          npm install -g @angular/cli
          npm install
      
      - name: Build Angular App
        run: ng build 

      - name: Deploy Lambda Functions
        run: |
          aws lambda update-function --function-name smooth-operators-Postusers --handler index.handler --runtime nodejs20.x --role arn:aws:lambda:ca-central-1:839728096237:function:smooth-operators-Postusers --zip-file fileb://./lambda-functions/lambda-bundle.zip
          aws lambda update-function --function-name smooth-operators-Getprojects --handler index.handler --runtime nodejs20.x --role arn:aws:lambda:ca-central-1:839728096237:function:smooth-operators-Getprojects --zip-file fileb://./lambda-functions/lambda-bundle.zip
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          folder: build
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '/*'


      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1-node20
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.WS_SECRET_ACCESS_KEYY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

