name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PATH: ${{ github.workspace }}/.npm-global/bin:$PATH
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        
    - name: Install dependencies
      run: yarn
      
    - name: Build project
      run: yarn build

    - name: Install Serverless Framework and Plugins
      run: |
        npm install -g serverless
        npm install -g serverless-sync-s3buckets

    - name: Deploy with Serverless Framework
      working-directory: smooth
      run: serverless deploy
