name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@latest
      

        
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
        
    - name: Install dependencies
      run: npm install
      
    - name: Create S3 bucket
      run: |
        aws s3 mb s3://batch2024-smooth --region ca-central-1
        
    - name: Deploy to S3 bucket
      run: |
        aws s3 sync dist/final-ui s3://batch2024-smooth --delete --region ca-central-1
      
    - name: Create CloudFront distribution
      run: |
        aws cloudfront create-distribution --distribution-config file://cloudfront-config.json
