name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
      
    - name: Deploy Serverless application
      run: |
        npm install -g serverless
        serverless deploy --stage dev --region ca-central-1
        
    - name: Create S3 bucket and CloudFront distribution
      run: |
        aws s3 mb s3://batch2024-smooth --region ca-central-1
        aws cloudfront create-distribution --distribution-config file://cloudfront-config.json
