name: Deploy Angular App to AWS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Angular CLI and Dependencies
        run: |
          npm install -g @angular/cli
          npm install
      
      - name: Build Angular App
        run: ng build 

      - name: Deploy Lambda Functions
        run: |
          aws lambda update-function --function-name smooth-operators-Postusers --handler index.handler --runtime nodejs20.x --role arn:aws:lambda:ca-central-1:839728096237:function:smooth-operators-Postusers --zip-file fileb://./lambda-functions/lambda-bundle.zip
          aws lambda update-function --function-name smooth-operators-Getprojects --handler index.handler --runtime nodejs20.x --role arn:aws:lambda:ca-central-1:839728096237:function:smooth-operators-Getprojects --zip-file fileb://./lambda-functions/lambda-bundle.zip
          
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          folder: build
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '/*'

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
